[package]
name = "lsf_env_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "lsf_env_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.19", features = ["extension-module"] }
numpy = "0.19"
rand = "0.8"